# Generated by Django 5.1.6 on 2025-02-21 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0002_mlscore"),
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="adververtiser",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisers.advertiser",
            ),
        ),
    ]
