# Generated by Django 5.1.6 on 2025-02-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("login", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("location", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
