# Generated by Django 5.1.6 on 2025-02-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "male"), ("FEMALE", "female")],
                max_length=1000,
                null=True,
            ),
        ),
    ]
