# Generated by Django 5.1.6 on 2025-02-14 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisers", "0002_mlscore"),
        ("campaigns", "0002_alter_campaign_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="advertiser_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="advertisers.advertiser",
            ),
        ),
    ]
