# Generated by Django 5.1.6 on 2025-02-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_alter_campaign_age_from_alter_campaign_age_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("now", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="sum_clicks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="sum_immpressions",
            field=models.IntegerField(default=0),
        ),
    ]
