# Generated by Django 5.1.6 on 2025-02-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_time_campaign_sum_clicks_campaign_sum_immpressions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="sum_clicks",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="sum_immpressions",
        ),
    ]
