# Generated by Django 5.1.6 on 2025-02-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_remove_campaign_sum_clicks_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Time",
        ),
    ]
