# Generated by Django 5.1.6 on 2025-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_campaignimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignimage",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
