# Generated by Django 5.1.6 on 2025-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertiser",
            fields=[
                (
                    "advertiser_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Рекламодатель",
                "verbose_name_plural": "Рекламодатели",
            },
        ),
    ]
